version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: intelligent-kitchen-db-dev
    environment:
      POSTGRES_DB: intelligent_kitchen_dev
      POSTGRES_USER: kitchen_user_dev
      POSTGRES_PASSWORD: kitchen_password_dev
    ports:
      - "55432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - kitchen-network-dev

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: intelligent-kitchen-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - kitchen-network-dev

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: intelligent-kitchen-backend-dev
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://kitchen_user_dev:kitchen_password_dev@postgres:5432/intelligent_kitchen_dev
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-super-secret-jwt-key-32chars-minimum-abcdef1234567890
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./database:/database
    networks:
      - kitchen-network-dev
    command: npm run dev

  # Frontend (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: intelligent-kitchen-frontend-dev
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - kitchen-network-dev
    command: npm run dev

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  kitchen-network-dev:
    driver: bridge